server:
  port: 9000

spring:
  application:
    name: "order"
  profiles:
    active: "default"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/ordersdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "order"
    description: "Panorama Shop Application"
    version: "1.0.0"

stripe:
  keys:
    secret: "sk_test_51OcWdTAQX8KpKNai4IvFkWouM4GsZxfo7T8SbcTWPjdjyusZQTvi7hQ1oVnV8IVKYdpovF5zA7C5dl4OdI7spMyB00ECgVOpqV"