server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    stream:
      bindings:
        emailConfirmation-in-0:
          destination: send-communication
          group: ${spring.application.name}
        orderDetails-in-0:
          destination: send-communication
          group: ${spring.application.name}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s